apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: Nexenta
    provider: github
    repository: edgefs-nodejs
  name: nexenta-edgefs-nodejs
spec:
  description: Imported application for Nexenta/edgefs-nodejs
  httpCloneURL: https://github.com/Nexenta/edgefs-nodejs.git
  org: Nexenta
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: edgefs-nodejs
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/Nexenta/edgefs-nodejs.git
